# Generated by Django 3.2.9 on 2021-11-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.IntegerField(verbose_name=5)),
                ('transaction_number', models.IntegerField(verbose_name=6)),
                ('paid_through', models.CharField(max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_date', models.DateTimeField()),
                ('customer_id', models.IntegerField(verbose_name=3)),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField(verbose_name=5)),
                ('branch_name', models.CharField(max_length=20)),
                ('branch_address', models.CharField(max_length=20)),
                ('manager_id', models.IntegerField(verbose_name=5)),
                ('cashier_id', models.IntegerField(verbose_name=5)),
            ],
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(verbose_name=3)),
                ('customer_id', models.IntegerField(verbose_name=3)),
                ('valid_till', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(verbose_name=3)),
                ('customer_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('email_id', models.CharField(max_length=20)),
                ('membership_period', models.IntegerField(verbose_name=3)),
                ('branch_id', models.IntegerField(verbose_name=5)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('salary', models.IntegerField(verbose_name=5)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(verbose_name=2)),
                ('item_name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='order_placed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name=4)),
                ('item_number', models.IntegerField(verbose_name=2)),
                ('time_order_placed', models.TimeField()),
                ('quantity', models.IntegerField(verbose_name=4)),
                ('customer_id', models.IntegerField(verbose_name=3)),
            ],
        ),
    ]
